name: wheather_app
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  #service
  http: ^1.2.1
  dio: ^5.4.3+1
  #location
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  #fonts
  google_fonts: ^6.2.1

  #animations
  lottie: ^3.1.0

  cupertino_icons: ^1.0.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/lotties/
    - assets/fonts/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
